### ISSUE TITLE
Ilhabela

### ISSUE THREAD

**Issue by gustavobio** [italocegatta/brmap#3]
Só para constar, em São Paulo há 645 municípios e no pacote há 644 polígonos para esse estado. Faltou Ilhabela. Só usei os polígonos de São Paulo, então não vi se há outras cidades faltando. No mais, valeu pelo pacote. Abraços.

**Comment by italocegatta** [comment]
[v0.1.0](https://github.com/italocegatta/brmap/commit/7263971bb50565d110265719b2e31866ddf4692c)
