### ISSUE TITLE
Shapes desatualizados

### ISSUE THREAD

**Issue by jjesusfilho** [italocegatta/brmap#4]
@italocegatta, os shapes dos estados individualmente considerados estão desatualizados. Se você baixar o shape do Brasil, ele está atualizado. Creio que seja melhor baixá-lo e criar o sfs dos estados a partir dele.

**Comment by italocegatta** [comment]
Obrigado @jjesusfilho, demorou mas chegou a atualização 😀 
[v0.1.0](https://github.com/italocegatta/brmap/commit/7263971bb50565d110265719b2e31866ddf4692c)
